### ISSUE TITLE
[solved] config.json cannot be created: permission denied

### ISSUE THREAD

**Issue by froggypaule** [mattermost/docker#106]
Hello all,
Yes I know this seems a recurring issue, I just has a lengthy exchange with [agriesser](https://forum.mattermost.com/t/unable-to-install-mattermost-via-docker-without-nginx-no-ports-showing/14062/17) who helped me along before I got stuck on the config.json issue.

It is a `docker compose -f docker-compose.yml -f docker-compose.without-nginx.yml` deployment on ubuntu 22.04, rootless docker, and password-less user.

Yes, I did the chown command:

```
ifb-user@mattermost:~/matterm$` ls -l volumes/app/mattermost/
total 24
drwxrwxr-x 2 2000 2000 4096 Sep 15 14:16 bleve-indexes
drwxrwxr-x 3 2000 2000 4096 Sep 15 14:16 client
drwxrwxr-x 2 2000 2000 4096 Sep 15 14:16 config
drwxrwxr-x 2 2000 2000 4096 Sep 15 14:16 data
drwxrwxr-x 2 2000 2000 4096 Sep 15 14:16 logs
drwxrwxr-x 2 2000 2000 4096 Sep 15 14:16 plugins

```

but the mattermost-1 container can't start:
```

matterm-mattermost-1  | Error: failed to load configuration: could not create config file: open /mattermost/config/config.json: permission denied
matterm-mattermost-1  | Usage:
matterm-mattermost-1  |   mattermost [flags]
matterm-mattermost-1  |   mattermost [command]
matterm-mattermost-1  | 

```

What on earth is crook? Many thanks.

**Comment by galamdring** [comment]
I'm having the same issue. permissions on volumes/app/mattermost are 2000:2000 but it errors trying to create config.json, permission denied.

**Comment by galamdring** [comment]
Spoke with Dave at GopherCon, and he suggested investigating what the actual user is inside the docker container. Either the docker "root" user doesn't have permissions the the directory, or 2000 isn't the actual user is inside the container.

**Comment by galamdring** [comment]
So the issue turns out to be that my user on the host machine (as the one running the docker command) did not have permissions to write to the folder. 
Docs day to run this command:
``` mkdir -p ./volumes/app/mattermost/{config,data,logs,plugins,client/plugins,bleve-indexes} && sudo chown -R 2000:2000 ./volumes/app/mattermost ```

I replaced this with:
``` mkdir -p ./volumes/app/mattermost/{config,data,logs,plugins,client/plugins,bleve-indexes} && sudo chown -R lmckechnie:2000 ./volumes/app/mattermost/  && sudo chmod -R 775 ./volumes/app/matterm
ost/ ```

By making my user the owner, and setting the permissions to make the directory group writable by the docker containers mattermost group, the app is now able to run.

I have seen other apps fix this by letting the end user control the userid through env vars. 

I also had to set a container_name for the postgres db, and update the MM_SQLSETTINGS_DATASOURCE in .env to match the configured container_name. Docker compose sets a unique container name if you don't specify it, and the dns in docker uses container_name not service name.

**Comment by froggypaule** [comment]
Hello, and thanks @galamdring for this. I'll try this and report here asap.

**Comment by froggypaule** [comment]
I am running out of luck: the above doesn't solve my problem. Not being a docker viz, how does one find out 

> what the actual user is inside the docker container.

?

**Comment by VA2XJM** [comment]
In my case `volumes` folder is owned by root:root.

Only `volumes/app/mattermost` and bellow are 2000:2000.

This is the way I done it (from my install procedure):
```
sudo mkdir -p ./volumes/app/mattermost/{config,data,logs,plugins,client-plugins}
sudo chown -R 2000:2000 ./volumes/app/mattermost
```

**Comment by froggypaule** [comment]
Hello! this is exactly what I did first thing, but no luck. I must do something stupid, the question is what?

**Comment by galamdring** [comment]
> I am running out of luck: the above doesn't solve my problem. Not being a docker viz, how does one find out 
> 
> > what the actual user is inside the docker container.
> 
> ?

The user inside the docker is being created as 2000. You can check this by launching the container with the /bin/bash command

`docker compose run -it  mattermost /bin/bash`

This should give you a shell inside the container, and you can check in /etc/passwd for the user id.

For me, the issue was that both I and the docker user needed write access to those files. Even if the docker user has the correct permissions, the docker process can't write it to the actual filesystem if the user running it doesn't have permissions.

You can either go the route I did, where I made my user the owner and left the group as 2000 and make the files group writable `chmod -R 775 [folder]`

Or

Leave the 2000:2000 on the files, set them group writeable and create a group with id 2000 and make your host user a part of it.

**Comment by galamdring** [comment]
Yeah, creating it with sudo will set root permissions. It's a silly way to
do it if you are creating the folders where you have write permission. But
its only the mattermost subfolders you actually need write permissions to.

The fact that you see 2000 as the owner/group means that your host system
doesn't have that user or group, so it can't show the name of it. This
means that you are left with only the everyone permission, in this case
just read access.

You could try `chmod -R 777 ./volumes/app/mattermost` and see if that
corrects it.

**Comment by froggypaule** [comment]
thanks again @galamdring! <docker run> cmd was what I was looking for. I truly did all what you suggest here. 
But I think I found the nut of the problem: my container is run as a rootless container, and uid/gid mapping behaves in a specific way I still have to understand.
I'll report asap.

**Comment by froggypaule** [comment]
Ok, I have solved it!  
So indeed, rootless docker map uids on host to uids on container differently; see https://medium.com/@tonistiigi/experimenting-with-rootless-docker-416c9ad8c0d6 for a nice pic explaining this.
Once one understands how the /etc/subuid file works, it suffices to chown the relevant directories with the correct uid: this depends on each situation and could be automated I am sure (no clue yet).

I you happy with that, you may close this.

**Comment by crossRT** [comment]
hi @froggypaule , may i know what's the final solution that u used to resolved this issue?

**Comment by froggypaule** [comment]
Hello! it just matter of reading https://medium.com/@tonistiigi/experimenting-with-rootless-docker-416c9ad8c0d6 and making sure the dir owner has the correct uuid as explained here 
>the container is run within the user (on host) namespace: one maps the container uid into the host uid namespace.
