### ISSUE TITLE
Matermost CLI not working in Docker deployment

### ISSUE THREAD

**Issue by gkoritnik** [mattermost/docker#65]
Executing Mattermost CLI commands are not successful. 
Missing credentials.

Error:
docker exec mattermost mmctl user list
Error: cannot read user credentials, maybe you need to use login first: stat /mattermost/.config/mmctl/config: no such file or directory

Mattermost server:
mattermost/mattermost-team-edition:6.0.2

**Comment by mrckndt** [comment]
@gkoritnik `mmctl` is working otherwise you won't see the error. You need to login to your instance or you the local mode. Because `mmctl` uses the Mattermost API it's not a drop-in replacement to the old `mattermost` binary command line tools. Please consult our documentation on `mmctl` https://docs.mattermost.com/manage/mmctl-command-line-tool.html.
